---
abstract: 'Creates a temporary instance of rsyslog to run tests against'
author:
  - 'David Dick <ddick@cpan.org>'
build_requires:
  Sys::Syslog: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  strict: '0'
  warnings: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-Rsyslog
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Config: '0'
  English: '0'
  Fcntl: '0'
  File::Spec: '0'
  File::Temp: '0'
  FileHandle: '0'
  POSIX: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
version: '0.07'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
